# Site settings
title: AW的个人博客
email: wqf_525@live.cn
description: > # this means to ignore newlines until "baseurl:"
  闫肃的博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://amazing" # the base hostname & protocol for your site
rss_url: /pages/feed.xml

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'

# Social account
twitter: amazingw
# weibo:    ID
github: amazingw
# codepen:  username
# dribbble: username

# avatar头像及Favicon
avatar: http://p2.gexing.com/touxiang/20130518/1919/519763a7c8ee7_200x200_3.jpg
favicon: http://ico.58pic.com/ajax/download?id=120277&format=ico

# disqus 设置
disqus:
  shortname: Amazing-W

# google analytics 设置
ga:
  id: UA-75184518-1
  url: auto

# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
sass:
  style: compressed
